string:
  actions: /mnt/windows/Enigma/Zebrafish/data/string/zebrafish/7955.protein.actions.v11.0.txt
  links: /mnt/windows/Enigma/Zebrafish/data/string/zebrafish/test.txt
  info: /mnt/windows/Enigma/Zebrafish/data/string/zebrafish/7955.protein.info.v11.0.txt
rnaseq:
  stringtie: /mnt/windows/Enigma/Zebrafish/data/rnaseq/stringtie
  salmon: /mnt/windows/Enigma/Zebrafish/data/rnaseq/salmon
  kallisto: /mnt/windows/Enigma/Zebrafish/data/rnaseq/kallisto
biomart: /mnt/windows/Enigma/Zebrafish/data/biomart/id_to_name_15_08_2020.tsv
zfin:
  expression: /mnt/windows/Enigma/Zebrafish/data/zfin/wildtype-expression_fish_2020.08.15.txt
  xpat: /mnt/windows/Enigma/Zebrafish/data/zfin/xpat_stage_anatomy_2020.08.15.txt
  ontology: /mnt/windows/Enigma/Zebrafish/data/zfin/stage_ontology_2020.08.15.txt
  fish_lines: /mnt/windows/Enigma/Zebrafish/data/zfin/wildtypes_fish_2020.08.15.txt
  fish_xpat: /mnt/windows/Enigma/Zebrafish/data/zfin/xpat_fish_2020.08.15.txt





